spring:
  h2:
    console:
      enabled: true

app:
  datasource:
    book:
      url: jdbc:h2:mem:book
      username: sa
      password: pass
    library:
      url: jdbc:h2:mem:library
      username: sa
      password: pass
    user:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: pass

